name: FIDOAC Server Build and Deploy
on: [workflow_dispatch]
jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install
        with:
          working-directory: ./fidoac_server

      - name: Build
        run: npm run build
        with:
          working-directory: ./fidoac_server

      - name: Copy dist via ssh
        uses: appleboy/scp-action@master
        with:
            working-directory: ./fidoac_server
            host: fido.westeurope.cloudapp.azure.com
            username: azureuser
            port: 22
            key: ${{ secrets.KEY }}
            source: "dist"
            target: "app"
