name: FIDOAC Server Build and Deploy
on: [workflow_dispatch]

defaults:
  run:
    shell: bash
    working-directory: ./fidoac_server

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy dist via ssh
        uses: appleboy/scp-action@master
        with:
            host: fido.westeurope.cloudapp.azure.com
            username: azureuser
            port: 22
            key: ${{ secrets.SSH_SK }}
            source: "./fidoac_server"
            target: "fidoac_server"
            strip_components: 1

      - name: Build docker
        uses: appleboy/ssh-action@master
        with:
          host: fido.westeurope.cloudapp.azure.com
          username: azureuser
          key: ${{ secrets.SSH_SK }}
          port: 22
          script: cd fidoac_server/fidoac_server && sudo docker build -t fidoac-server .

      - name: Run docker
        uses: appleboy/ssh-action@master
        with:
          host: fido.westeurope.cloudapp.azure.com
          username: azureuser
          key: ${{ secrets.SSH_SK }}
          port: 22
          script: sudo docker rm -f fidoac-server && sudo docker run -d --name fidoac-server -p 8080:8080 fidoac-server
      - name: Upload fido-ac.js to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload --account-name fidoacsource --sas-token ${{ secrets.AZURE_BLOB_SAS_TOKEN }} --container-name '$web' --file fidoac_app_server/dist/public/fido-ac.js --overwrite
