name: FIDOAC Server Build and Deploy
on: [workflow_dispatch]

defaults:
  run:
    shell: bash
    working-directory: ./fidoac_server

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy dist via ssh
        uses: appleboy/scp-action@master
        with:
            host: fido.westeurope.cloudapp.azure.com
            username: azureuser
            port: 22
            key: ${{ secrets.SSH_SK }}
            source: "./fidoac_server"
            target: "fidoac_server"
            strip_components: 1

      - name: Build docker
        uses: appleboy/ssh-action@master
        with:
          host: fido.westeurope.cloudapp.azure.com
          username: azureuser
          key: ${{ secrets.SSH_SK }}
          port: 22
          script: cd fidoac_server && docker build -t fidoac-server .

      - name: Run docker
        uses: appleboy/ssh-action@master
        with:
          host: fido.westeurope.cloudapp.azure.com
          username: azureuser
          key: ${{ secrets.SSH_SK }}
          port: 22
          script: docker rm -f fidoac-server && docker run --name fidoac-server  fidoac-server
