name: FIDOAC Server Build and Deploy
on: [workflow_dispatch]

defaults:
  run:
    shell: bash
    working-directory: ./fidoac_server

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: ./fidoac_server/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy dist via ssh
        uses: appleboy/scp-action@master
        with:
            host: fido.westeurope.cloudapp.azure.com
            username: azureuser
            port: 22
            key: ${{ secrets.SSH_SK }}
            source: "./fidoac_server/dist"
            target: "app"
